### ISSUE TITLE
Convert breast cancer examples to notebook format

### ISSUE THREAD

**Issue by DilumAluthge** [bcbi/PredictMD.jl#107]
@mirestrepo Can you convert the breast cancer examples to notebook format?

**Comment by mirestrepo** [comment]
Absolutely! I'm also exploring https://github.com/fredrikekre/Literate.jl that would let us write examples in a way that can be generated for docs, notebooks and scripts ... so that may be a more elegant solution.  I will only be able to work on this next week though as I have a deadline for Liz. Do you want to set up Documenter in the mean time?

**Comment by DilumAluthge** [comment]
Literate looks like the perfect solution - it looks like we can generate Documenter pages, plain text Julia files, and Jupyter notebooks all from the same source.

Let's aim to meet sometime next week and set up Documenter and Literate.
